# Global settings applied to the whole site.
# “base” is the directory to change to before starting build.
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html so the SPA router works on refresh.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200